before:
  hooks:
    - go mod tidy
    - rm -rf dist/
    - ./scripts/completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
    - completions/*
    rlcp: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: serve
    tap:
      owner: planta7
      name: homebrew-tap
    url_template: "https://github.com/planta7/serve/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/planta7/serve"
    description: "Create a local server from any location on your computer (soon you will be able to expose it to the Internet as well ;))"
    license: "MIT"
    install: |
      bin.install "serve"
      bash_completion.install "completions/serve.bash" => "serve"
      zsh_completion.install "completions/serve.zsh" => "_serve"
      fish_completion.install "completions/serve.fish"
    caveats: "Thanks for installing serve!"
