before:
  hooks:
    - go mod tidy
    - rm -rf dist/
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: serve
    tap:
      owner: planta7
      name: homebrew-tap
    url_template: "https://github.com/planta7/serve/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/planta7/serve"
    description: "Create a local server from any location on your computer (soon you will be able to expose it to the Internet as well ;))"
    license: "MIT"
    install: |
      bin.install "serve"
#chocolateys:
#  - name: serve
#    authors: Roberto García
#    project_url: https://github.com/planta7/serve
#    url_template: "https://github.com/planta7/serve/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#    icon_url: https://github.com/planta7/serve/blob/main/assets/logo.png
#    copyright: 2023 Roberto García
#    license_url: https://github.com/planta7/serve/blob/main/LICENSE
#    project_source_url: https://github.com/planta7/serve
#    docs_url: https://github.com/planta7/serve/blob/main/README.md
#    bug_tracker_url: https://github.com/planta7/serve/issues
#    tags: "cli golang local http-server development-tools"
#    summary: Create a local server from any location on your computer
#    description: |
#      {{ .ProjectName }} installer package.
#      `serve` allows you to easily expose any content on your computer through a local web server.
#    release_notes: "https://github.com/planta7/serve/releases/tag/v{{ .Version }}"
#    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
